# Generated by Django 4.2.1 on 2023-05-24 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OauthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=20, unique=True)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('expires', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ZoomProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoom_id', models.CharField(max_length=100, unique=True)),
                ('dept', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('pic_url', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('extension_number', models.IntegerField(blank=True, default=None, null=True)),
                ('presence_status', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('presence_status_updated', models.DateTimeField(blank=True, default=None, null=True)),
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='zoom_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CallingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('zoom_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calling_plans', to='teamsite_zoom.zoomprofile')),
            ],
        ),
        migrations.CreateModel(
            name='AssignedNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True)),
                ('location', models.CharField(max_length=100)),
                ('zoom_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_numbers', to='teamsite_zoom.zoomprofile')),
            ],
        ),
    ]
